name: Release
run-name: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || '' }}

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
    branches:
      - main
      - master
      - dev

permissions:
  contents: write

jobs:
  publish-tauri:
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/dev'
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-14'
            args: '--target aarch64-apple-darwin'
            display_name: 'macOS-ARM64'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
            display_name: 'macOS-Intel'
          - platform: 'windows-latest'
            args: '--target x86_64-pc-windows-msvc'
            display_name: 'Windows-x64-Standard'
          - platform: 'windows-latest'
            args: '--target aarch64-pc-windows-msvc'
            display_name: 'Windows-ARM64-Standard'
          - platform: 'windows-latest'
            args: '--target x86_64-pc-windows-msvc --config src-tauri/webview2-x64-config.json'
            webview2_type: 'fixed_x64'
            display_name: 'Windows-x64-FixedWebView2'
          - platform: 'windows-latest'
            args: '--target aarch64-pc-windows-msvc --config src-tauri/webview2-arm64-config.json'
            webview2_type: 'fixed_arm64'
            display_name: 'Windows-ARM64-FixedWebView2'

    runs-on: ${{ matrix.platform }}
    name: ${{ matrix.display_name }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Get Version (Windows)
        if: matrix.platform == 'windows-latest'
        id: get_version_windows
        shell: pwsh
        run: |
          $VERSION = (node -p "require('./package.json').version")
          echo "version=v$VERSION" >> $env:GITHUB_OUTPUT

      - name: Get Version (Unix)
        if: matrix.platform != 'windows-latest'
        id: get_version_unix
        shell: bash
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=v$VERSION" >> $GITHUB_OUTPUT

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'x86_64-apple-darwin' || matrix.platform == 'macos-14' && 'aarch64-apple-darwin' || contains(matrix.args, 'aarch64-pc-windows-msvc') && 'aarch64-pc-windows-msvc' || '' }}

      - name: Install dependencies (macOS)
        if: matrix.platform == 'macos-latest' || matrix.platform == 'macos-14'
        run: |
          brew install openssl@3

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install dependencies
        run: pnpm install

      - name: Prepare WebView2 Fixed Runtime (Windows x64)
        if: matrix.platform == 'windows-latest' && matrix.webview2_type == 'fixed_x64'
        shell: pwsh
        run: |
          mkdir -p src-tauri/webview2-runtime/x64
          Invoke-WebRequest -Uri "https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/949b4951-7f54-4504-8a73-ccad659afdb1/Microsoft.WebView2.FixedVersionRuntime.134.0.3124.72.x64.cab" -OutFile "webview2-runtime.cab"
          cmd /c "expand webview2-runtime.cab -F:* .\src-tauri\webview2-runtime\x64\"
          
          # 创建配置文件
          $config = @{
            bundle = @{
              windows = @{
                webviewInstallMode = @{
                  type = "fixedRuntime"
                  path = "./webview2-runtime/x64/"
                }
              }
            }
          }
          $configJson = ConvertTo-Json $config -Depth 10
          Set-Content -Path "src-tauri/webview2-x64-config.json" -Value $configJson

      - name: Prepare WebView2 Fixed Runtime (Windows ARM64)
        if: matrix.platform == 'windows-latest' && matrix.webview2_type == 'fixed_arm64'
        shell: pwsh
        run: |
          mkdir -p src-tauri/webview2-runtime/arm64
          Invoke-WebRequest -Uri "https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/abc49133-bb96-41e6-a555-8ea087ff4564/Microsoft.WebView2.FixedVersionRuntime.134.0.3124.72.arm64.cab" -OutFile "webview2-runtime.cab"
          cmd /c "expand webview2-runtime.cab -F:* .\src-tauri\webview2-runtime\arm64\"
          
          # 创建配置文件
          $config = @{
            bundle = @{
              windows = @{
                webviewInstallMode = @{
                  type = "fixedRuntime"
                  path = "./webview2-runtime/arm64/"
                }
              }
            }
          }
          $configJson = ConvertTo-Json $config -Depth 10
          Set-Content -Path "src-tauri/webview2-arm64-config.json" -Value $configJson

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v') && matrix.platform == 'macos-14'
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version_unix.outputs.version }}
          name: ${{ steps.get_version_unix.outputs.version }}
          draft: false
          prerelease: false

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with: 
          tagName: ${{ matrix.platform == 'windows-latest' && steps.get_version_windows.outputs.version || steps.get_version_unix.outputs.version }}
          releaseName: ${{ matrix.platform == 'windows-latest' && steps.get_version_windows.outputs.version || steps.get_version_unix.outputs.version }}
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}
          includeUpdaterJson: true
      
      # 为dev分支上传构建产物
      - name: Upload Dev Build Artifacts
        if: github.ref == 'refs/heads/dev'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.display_name }}-build
          path: |
            src-tauri/target/*/release/bundle/msi/*.msi
            src-tauri/target/*/release/bundle/nsis/*.exe
            src-tauri/target/*/release/bundle/dmg/*.dmg
            src-tauri/target/*/release/bundle/deb/*.deb
            src-tauri/target/*/release/bundle/appimage/*.AppImage
            src-tauri/target/*/release/bundle/macos/*.app
          retention-days: 7