name: Rust Clippy

on:
  pull_request:
    branches: [ main, master, dev ]
    paths:
      - 'src-tauri/**/*.rs'
      - 'src-tauri/Cargo.toml'
      - 'src-tauri/Cargo.lock'
      - 'src-tauri/.clippy.toml'

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
      
      - name: Run Clippy (基本检查)
        run: cd src-tauri && cargo clippy -- -D warnings
      
      - name: Run Clippy (扩展检查)
        run: cd src-tauri && cargo clippy -- -W clippy::pedantic -W clippy::nursery -W clippy::unwrap_used
        
      - name: 添加PR评论
        if: github.event_name == 'pull_request'
        uses: actions-ecosystem/action-create-comment@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ## Clippy 检查已完成
            
            ✅ 基本检查通过
            
            如果你想查看更多建议，可以查看工作流的详细日志。 